# coding: utf-8
"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from blllib import ProviderApi


class TestProviderApi(unittest.TestCase):
    """ProviderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProviderApi()

    def tearDown(self) -> None:
        pass

    def test_clients_get_client(self) -> None:
        """Test case for clients_get_client"""
        pass

    def test_data_list(self) -> None:
        """Test case for data_list"""
        pass

    def test_each_data_get(self) -> None:
        """Test case for each_data_get"""
        pass


if __name__ == "__main__":
    unittest.main()
