# coding: utf-8
"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from blllib import ServerApi


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerApi()

    def tearDown(self) -> None:
        pass

    def test_status_get(self) -> None:
        """Test case for status_get"""
        pass


if __name__ == "__main__":
    unittest.main()
