# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from blllib import StatusCode

class TestStatusCode(unittest.TestCase):
    """StatusCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusCode(self):
        """Test StatusCode"""
        # inst = StatusCode()

if __name__ == '__main__':
    unittest.main()
