# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.koyo_create200_response import KoyoCreate200Response

class TestKoyoCreate200Response(unittest.TestCase):
    """KoyoCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoyoCreate200Response:
        """Test KoyoCreate200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoyoCreate200Response`
        """
        model = KoyoCreate200Response()
        if include_optional:
            return KoyoCreate200Response(
                koyo_id = 'wqyzkkciwg_n-wcqj_hcorcasz_uagjkdkamsgqefb_lv_h',
                koyo_name = '0',
                koyo_description = '',
                need_external = [
                    'example_id'
                    ],
                koyo_params = {
                    'key' : ''
                    },
                koyo_scales = [
                    1.337
                    ],
                koyo_data_ids = [
                    ''
                    ],
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                license = '',
                ext_licenses = [
                    ''
                    ],
                first_entry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_entry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                api_key = ''
            )
        else:
            return KoyoCreate200Response(
                koyo_id = 'wqyzkkciwg_n-wcqj_hcorcasz_uagjkdkamsgqefb_lv_h',
                koyo_name = '0',
                koyo_description = '',
                need_external = [
                    'example_id'
                    ],
                koyo_params = {
                    'key' : ''
                    },
                koyo_scales = [
                    1.337
                    ],
                koyo_data_ids = [
                    ''
                    ],
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                license = '',
                ext_licenses = [
                    ''
                    ],
                first_entry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_entry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                api_key = '',
        )
        """

    def testKoyoCreate200Response(self):
        """Test KoyoCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
