# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.koyo_versions import KoyoVersions

class TestKoyoVersions(unittest.TestCase):
    """KoyoVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKoyoVersions(self):
        """Test KoyoVersions"""
        # inst = KoyoVersions()

if __name__ == '__main__':
    unittest.main()
