# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.algorithm_api import AlgorithmApi


class TestAlgorithmApi(unittest.TestCase):
    """AlgorithmApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlgorithmApi()

    def tearDown(self) -> None:
        pass

    def test_algorithm_list(self) -> None:
        """Test case for algorithm_list

        """
        pass

    def test_each_algorithm_data_get(self) -> None:
        """Test case for each_algorithm_data_get

        """
        pass

    def test_each_algorithm_data_update(self) -> None:
        """Test case for each_algorithm_data_update

        """
        pass

    def test_each_algorithm_get(self) -> None:
        """Test case for each_algorithm_get

        """
        pass

    def test_each_algorithm_update(self) -> None:
        """Test case for each_algorithm_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
