# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.external_information_api import ExternalInformationApi


class TestExternalInformationApi(unittest.TestCase):
    """ExternalInformationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExternalInformationApi()

    def tearDown(self) -> None:
        pass

    def test_example_info_get(self) -> None:
        """Test case for example_info_get

        Get example data endpoint
        """
        pass

    def test_example_info_post(self) -> None:
        """Test case for example_info_post

        Post example data endpoint
        """
        pass

    def test_ext_info_get(self) -> None:
        """Test case for ext_info_get

        """
        pass

    def test_ext_info_list(self) -> None:
        """Test case for ext_info_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
