# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.koyo_koyo_data import KoyoKoyoData

class TestKoyoKoyoData(unittest.TestCase):
    """KoyoKoyoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoyoKoyoData:
        """Test KoyoKoyoData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoyoKoyoData`
        """
        model = KoyoKoyoData()
        if include_optional:
            return KoyoKoyoData(
                koyo_data_id = '',
                koyo_id = 'wqyzkkciwg_n-wcqj_hcorcasz_uagjkdkamsgqefb_lv_h',
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                koyo_scale = 1.337,
                content_type = 'image',
                content = 'YQ==',
                entry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                target_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return KoyoKoyoData(
                koyo_data_id = '',
                koyo_id = 'wqyzkkciwg_n-wcqj_hcorcasz_uagjkdkamsgqefb_lv_h',
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                koyo_scale = 1.337,
                content_type = 'image',
                content = 'YQ==',
                entry_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                target_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testKoyoKoyoData(self):
        """Test KoyoKoyoData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
