# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.koyo_koyo_data_create_or_update import KoyoKoyoDataCreateOrUpdate

class TestKoyoKoyoDataCreateOrUpdate(unittest.TestCase):
    """KoyoKoyoDataCreateOrUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoyoKoyoDataCreateOrUpdate:
        """Test KoyoKoyoDataCreateOrUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoyoKoyoDataCreateOrUpdate`
        """
        model = KoyoKoyoDataCreateOrUpdate()
        if include_optional:
            return KoyoKoyoDataCreateOrUpdate(
                koyo_id = 'wqyzkkciwg_n-wcqj_hcorcasz_uagjkdkamsgqefb_lv_h',
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                koyo_scale = 1.337,
                content_type = 'image',
                content = 'YQ=='
            )
        else:
            return KoyoKoyoDataCreateOrUpdate(
                koyo_id = 'wqyzkkciwg_n-wcqj_hcorcasz_uagjkdkamsgqefb_lv_h',
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                koyo_scale = 1.337,
                content_type = 'image',
                content = 'YQ==',
        )
        """

    def testKoyoKoyoDataCreateOrUpdate(self):
        """Test KoyoKoyoDataCreateOrUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
