# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ext_info_revoke200_response import ExtInfoRevoke200Response

class TestExtInfoRevoke200Response(unittest.TestCase):
    """ExtInfoRevoke200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtInfoRevoke200Response:
        """Test ExtInfoRevoke200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtInfoRevoke200Response`
        """
        model = ExtInfoRevoke200Response()
        if include_optional:
            return ExtInfoRevoke200Response(
                extinfo_id = 'example_id',
                api_key = ''
            )
        else:
            return ExtInfoRevoke200Response(
                extinfo_id = 'example_id',
                api_key = '',
        )
        """

    def testExtInfoRevoke200Response(self):
        """Test ExtInfoRevoke200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
