# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.koyo_koyo_infomation_create import KoyoKoyoInfomationCreate

class TestKoyoKoyoInfomationCreate(unittest.TestCase):
    """KoyoKoyoInfomationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoyoKoyoInfomationCreate:
        """Test KoyoKoyoInfomationCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoyoKoyoInfomationCreate`
        """
        model = KoyoKoyoInfomationCreate()
        if include_optional:
            return KoyoKoyoInfomationCreate(
                koyo_name = '0',
                koyo_description = '',
                need_external = [
                    'example_id'
                    ],
                koyo_params = {
                    'key' : ''
                    },
                koyo_scales = [
                    1.337
                    ],
                koyo_data_ids = [
                    ''
                    ],
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                license = '',
                ext_licenses = [
                    ''
                    ]
            )
        else:
            return KoyoKoyoInfomationCreate(
                koyo_name = '0',
                koyo_description = '',
                need_external = [
                    'example_id'
                    ],
                koyo_params = {
                    'key' : ''
                    },
                koyo_scales = [
                    1.337
                    ],
                koyo_data_ids = [
                    ''
                    ],
                version = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026',
                license = '',
                ext_licenses = [
                    ''
                    ],
        )
        """

    def testKoyoKoyoInfomationCreate(self):
        """Test KoyoKoyoInfomationCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
