# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.each_koyo_update_request import EachKoyoUpdateRequest

class TestEachKoyoUpdateRequest(unittest.TestCase):
    """EachKoyoUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EachKoyoUpdateRequest:
        """Test EachKoyoUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EachKoyoUpdateRequest`
        """
        model = EachKoyoUpdateRequest()
        if include_optional:
            return EachKoyoUpdateRequest(
                update_koyo = openapi_client.models.koyo_information.Koyo information(
                    koyo_id = null, 
                    koyo_name = '0', 
                    koyo_description = '', 
                    need_external = [
                        'example_id'
                        ], 
                    koyo_params = {
                        'key' : ''
                        }, 
                    koyo_scales = [
                        1.337
                        ], 
                    koyo_data_ids = [
                        ''
                        ], 
                    version = null, 
                    license = '', 
                    ext_licenses = [
                        ''
                        ], )
            )
        else:
            return EachKoyoUpdateRequest(
                update_koyo = openapi_client.models.koyo_information.Koyo information(
                    koyo_id = null, 
                    koyo_name = '0', 
                    koyo_description = '', 
                    need_external = [
                        'example_id'
                        ], 
                    koyo_params = {
                        'key' : ''
                        }, 
                    koyo_scales = [
                        1.337
                        ], 
                    koyo_data_ids = [
                        ''
                        ], 
                    version = null, 
                    license = '', 
                    ext_licenses = [
                        ''
                        ], ),
        )
        """

    def testEachKoyoUpdateRequest(self):
        """Test EachKoyoUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
