# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.types_versions import TypesVersions

class TestTypesVersions(unittest.TestCase):
    """TypesVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesVersions(self):
        """Test TypesVersions"""
        # inst = TypesVersions()

if __name__ == '__main__':
    unittest.main()
