# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.each_koyo_data_new_request import EachKoyoDataNewRequest

class TestEachKoyoDataNewRequest(unittest.TestCase):
    """EachKoyoDataNewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EachKoyoDataNewRequest:
        """Test EachKoyoDataNewRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EachKoyoDataNewRequest`
        """
        model = EachKoyoDataNewRequest()
        if include_optional:
            return EachKoyoDataNewRequest(
                update_data = openapi_client.models.koyo_data.Koyo data(
                    koyo_id = null, 
                    version = null, 
                    koyo_scale = null, 
                    content_type = null, 
                    content = 'YQ==', )
            )
        else:
            return EachKoyoDataNewRequest(
                update_data = openapi_client.models.koyo_data.Koyo data(
                    koyo_id = null, 
                    version = null, 
                    koyo_scale = null, 
                    content_type = null, 
                    content = 'YQ==', ),
        )
        """

    def testEachKoyoDataNewRequest(self):
        """Test EachKoyoDataNewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
