# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ext_info_versions import ExtInfoVersions

class TestExtInfoVersions(unittest.TestCase):
    """ExtInfoVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtInfoVersions(self):
        """Test ExtInfoVersions"""
        # inst = ExtInfoVersions()

if __name__ == '__main__':
    unittest.main()
