# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from algorithm_lib.models.algorithm_data_type import AlgorithmDataType

class TestAlgorithmDataType(unittest.TestCase):
    """AlgorithmDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlgorithmDataType(self):
        """Test AlgorithmDataType"""
        # inst = AlgorithmDataType()

if __name__ == '__main__':
    unittest.main()
