# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from algorithm_lib.models.ext_info_delete200_response import ExtInfoDelete200Response

class TestExtInfoDelete200Response(unittest.TestCase):
    """ExtInfoDelete200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtInfoDelete200Response:
        """Test ExtInfoDelete200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtInfoDelete200Response`
        """
        model = ExtInfoDelete200Response()
        if include_optional:
            return ExtInfoDelete200Response(
                delete_extinfo_id = 'HOGE_ID'
            )
        else:
            return ExtInfoDelete200Response(
                delete_extinfo_id = 'HOGE_ID',
        )
        """

    def testExtInfoDelete200Response(self):
        """Test ExtInfoDelete200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
