# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.types_geo_json_polygon import TypesGeoJSONPolygon

class TestTypesGeoJSONPolygon(unittest.TestCase):
    """TypesGeoJSONPolygon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypesGeoJSONPolygon:
        """Test TypesGeoJSONPolygon
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypesGeoJSONPolygon`
        """
        model = TypesGeoJSONPolygon()
        if include_optional:
            return TypesGeoJSONPolygon(
                type = 'Polygon',
                coordinates = [
                    [
                        null
                        ]
                    ]
            )
        else:
            return TypesGeoJSONPolygon(
                type = 'Polygon',
                coordinates = [
                    [
                        null
                        ]
                    ],
        )
        """

    def testTypesGeoJSONPolygon(self):
        """Test TypesGeoJSONPolygon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
