# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.provider_request_type import ProviderRequestType

class TestProviderRequestType(unittest.TestCase):
    """ProviderRequestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderRequestType(self):
        """Test ProviderRequestType"""
        # inst = ProviderRequestType()

if __name__ == '__main__':
    unittest.main()
