# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.algorithm_versions import AlgorithmVersions

class TestAlgorithmVersions(unittest.TestCase):
    """AlgorithmVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlgorithmVersions(self):
        """Test AlgorithmVersions"""
        # inst = AlgorithmVersions()

if __name__ == '__main__':
    unittest.main()
