# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from algorithm_lib.models.hoge_get200_response_inner import HogeGet200ResponseInner

class TestHogeGet200ResponseInner(unittest.TestCase):
    """HogeGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HogeGet200ResponseInner:
        """Test HogeGet200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HogeGet200ResponseInner`
        """
        model = HogeGet200ResponseInner()
        if include_optional:
            return HogeGet200ResponseInner(
                content_type = 'image/jpeg',
                image = 'YQ=='
            )
        else:
            return HogeGet200ResponseInner(
                content_type = 'image/jpeg',
                image = 'YQ==',
        )
        """

    def testHogeGet200ResponseInner(self):
        """Test HogeGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
