# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from algorithm_lib.api.external_information_api import ExternalInformationApi


class TestExternalInformationApi(unittest.TestCase):
    """ExternalInformationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExternalInformationApi()

    def tearDown(self) -> None:
        pass

    def test_each_ext_info_get(self) -> None:
        """Test case for each_ext_info_get

        """
        pass

    def test_ext_info_list(self) -> None:
        """Test case for ext_info_list

        """
        pass

    def test_hoge_get(self) -> None:
        """Test case for hoge_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
