# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from algorithm_lib.models.provider_versions import ProviderVersions

class TestProviderVersions(unittest.TestCase):
    """ProviderVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderVersions(self):
        """Test ProviderVersions"""
        # inst = ProviderVersions()

if __name__ == '__main__':
    unittest.main()
