# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from algorithm_lib.models.algorithm_create_request import AlgorithmCreateRequest

class TestAlgorithmCreateRequest(unittest.TestCase):
    """AlgorithmCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlgorithmCreateRequest:
        """Test AlgorithmCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlgorithmCreateRequest`
        """
        model = AlgorithmCreateRequest()
        if include_optional:
            return AlgorithmCreateRequest(
                algorithm = algorithm_lib.models.algorithm/algorithm_infomation_create.Algorithm.AlgorithmInfomationCreate(
                    algorithm_name = '', 
                    algorithm_description = '', 
                    need_external = [
                        'HOGE_ID'
                        ], 
                    algorithm_scales = [
                        1.337
                        ], 
                    algorithm_data_ids = [
                        ''
                        ], )
            )
        else:
            return AlgorithmCreateRequest(
                algorithm = algorithm_lib.models.algorithm/algorithm_infomation_create.Algorithm.AlgorithmInfomationCreate(
                    algorithm_name = '', 
                    algorithm_description = '', 
                    need_external = [
                        'HOGE_ID'
                        ], 
                    algorithm_scales = [
                        1.337
                        ], 
                    algorithm_data_ids = [
                        ''
                        ], ),
        )
        """

    def testAlgorithmCreateRequest(self):
        """Test AlgorithmCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
