import blllib

print(dir(blllib))
# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = blllib.AdminApi()

    def tearDown(self) -> None:
        pass

    def test_algorithm_create(self) -> None:
        """Test case for algorithm_create
        """
        pass

    def test_algorithm_delete(self) -> None:
        """Test case for algorithm_delete

        """
        pass

    def test_client_create(self) -> None:
        """Test case for client_create

        """
        pass

    def test_client_delete(self) -> None:
        """Test case for client_delete

        """
        pass

    def test_ext_info_create(self) -> None:
        """Test case for ext_info_create

        """
        pass

    def test_ext_info_delete(self) -> None:
        """Test case for ext_info_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
