# coding: utf-8

"""
    BeLifeline Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.7.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from blllib import models

class TestKoyoDataType(unittest.TestCase):
    """KoyoDataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKoyoDataType(self):
        """Test KoyoDataType"""
        # inst = KoyoDataType()

if __name__ == '__main__':
    unittest.main()
